name: Docker Kubernetes

on: workflow_dispatch

jobs:

  dockerCI:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub registry
        uses: docker/login-action@v2
        with:
          username: weronika00
          password: ${{ secrets.CHMURKI_DOCKERHUB }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64,linux/arm64/v8
          file: ./Dockerfile
          push: true
          tags: 'weronika00/hefalump:${{ vars.VERSION }}'
          labels: ${{ steps.meta.output.labels }}
         
  kubernetesCI:

    runs-on: ubuntu-latest
    needs: dockerCI

    steps:
      - name: Get config repo
        uses: actions/checkout@v4
        with:
          repository: weronika0/config_repo
          ref: master
          token: ${{ secrets.TOKEN }}
      
      - name: Update version in config repo
        run: |
          git config user.name 'weronika0'
          git config user.email 'weronika.nowak@pollub.edu.pl'
          sed -i 's|image: weronika00/hefalump:.*|image: weronika00/hefalump:${{ vars.VERSION }}|g' ./deployment.yaml
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update ${{ vars.VERSION }}'
          git push origin master
